### ISSUE TITLE
Is this outdated?

### ISSUE THREAD

**Issue by ericclemmons** [apollostack/apollo-starter-kit#16]
The docs reference getting `apolloExpress` from `apollo-server`, not `graphql-tools` (which this branch uses), and also `graphiql` is a config option in this branch versus a separate route in the docs:
> http://docs.apollostack.com/apollo-server/graphiql.html

**Comment by helfer** [comment]
Yes, it's somewhat outdated. The demo and tutorial use apollo-server 0.1, so we have to keep it this way for the starter kit.

**Comment by ericclemmons** [comment]
Which docs should I use for the latest version, then?

**Comment by helfer** [comment]
The ones on docs.apollostack.com. I don't think there are any other ones. There's also a migration guide there.

**Comment by ericclemmons** [comment]
Ok, I'll check the docs & not look at the starter kits then.  Thanks!
