### ISSUE TITLE
Cannot read property 'src/providers/en_US/address' of undefined

### ISSUE THREAD

**Issue by batjko** [apollostack/apollo-starter-kit#2]
Hi guys,
Just trying to go through the guide on the Apollo server page:
http://docs.apollostack.com/apollo-server/guide.html

Just cloned the boilerplate, ran `npm install`, and then `npm start`, et voila: some issue with casual-browserify, apparently. 

This is on WIndows 10 btw.
I can see this package is used for generating fake data, e.g. the mocks the `apollo-tools` provide?
Know of any reason why it may run into the below issue?

**Error stack:**

```shell
> npm start

> apollo-starter-kit@0.1.0 start c:\Git\apollo-test
> babel-node ./server.js

c:\Git\apollo-test\node_modules\casual-browserify\src\casual_browserify.js:61
        return locales[locale][provider] || {};
                              ^

TypeError: Cannot read property 'src/providers/en_US/address' of undefined
    at safe_require (c:\Git\apollo-test\node_modules\casual-browserify\src\casual_browserify.js:61:24)
    at c:\Git\apollo-test\node_modules\casual-browserify\src\casual_browserify.js:100:6
    at Array.forEach (native)
    at Object.<anonymous> (c:\Git\apollo-test\node_modules\casual-browserify\src\casual_browserify.js:97:14)
    at Object.<anonymous> (c:\Git\apollo-test\node_modules\casual-browserify\src\casual_browserify.js:125:32)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (c:\Git\apollo-test\node_modules\babel-register\lib\node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! apollo-starter-kit@0.1.0 start: `babel-node ./server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apollo-starter-kit@0.1.0 start script 'babel-node ./server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apollo-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apollo-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apollo-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Git\apollo-test\npm-debug.log
```

**Comment by stubailo** [comment]
Hey - we're still fixing things up for an alpha launch next week, so things are a bit in progress for the next few days!

**Comment by batjko** [comment]
Not a problem, @stubailo. I didn't expect perfection at this early stage. 
Just thought I'd log it for your information.

**Comment by stubailo** [comment]
Thanks for the heads up!

**Comment by helfer** [comment]
@bajtko Can you give it another try and see if you still run into the same problem? Might be something we have to fix upstream.

**Comment by batjko** [comment]
@helfer Yup, just cloned a fresh copy... exact same error, I'm afraid.
![image](https://cloud.githubusercontent.com/assets/7287076/14686127/613e0e3e-072f-11e6-8a18-ed9c8949a7f6.png)

**Comment by helfer** [comment]
Ok, I see. Given that we don't really need casual, I'm going to rewrite the little bit of code that I have to in order to be able to remove the dependency.

**Comment by helfer** [comment]
@bajtko It should now be fixed in graphql-tools with this PR https://github.com/apollostack/graphql-tools/pull/39
Running npm update should be enough to make the error go away. :)

**Comment by batjko** [comment]
Woohoo :tada: Indeed it is.
Thanks a lot.
