### ISSUE TITLE
Unnecessary babel-loader dependency in package.json

### ISSUE THREAD

**Issue by batjko** [apollostack/apollo-starter-kit#6]
Hi guys,

After a fresh clone of this repo and using the `server-only` branch, as per the tutorial in the docs, `npm install` gives me this error:
![image](https://cloud.githubusercontent.com/assets/7287076/15074215/a54df8b0-1395-11e6-8a89-d4d304516389.png)

While I am perfectly happy to install webpack manually, I thought I'd log the issue nonetheless. Shouldn't it just be added as a dev dependency?

**Comment by stubailo** [comment]
You don't actually need webpack to run anything.. unfortunately some of the dependencies we _do_ need include it as a peer dependency. Not sure how to get around this - adding Webpack to the dependencies seems like the wrong choice.

**Comment by stubailo** [comment]
Oh, I think we just need to remove: https://github.com/apollostack/apollo-starter-kit/blob/2ddefd219595cbabcd0ed3c1b4f4f85f9a03dcc3/package.json#L36

@helfer

**Comment by helfer** [comment]
Yup, you're right. I removed in the server-only and server-tutorial-solution branches.

**Comment by batjko** [comment]
OK great,  thanks.  :thumbsup:
